# Generated by Django 5.2.1 on 2026-03-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
                ('tech_stack', models.CharField(max_length=250)),
            ],
        ),
    ]
