# Generated by Django 5.2.1 on 2026-03-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_id',
        ),
    ]
