# Generated by Django 5.2.12 on 2026-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyche', '0002_alter_courses_options_remove_courses_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
