# Generated by Django 5.2.1 on 2026-04-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyche', '0003_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
